[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["cd rag-web-app/backend && pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd rag-web-app/backend && python app.py"

