[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.setuptools", "python39Packages.wheel"]

[phases.install]
cmds = [
  "cd backend",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "cd backend && python3 app.py"

