[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.setuptools", "python39Packages.wheel", "python39Packages.virtualenv"]

[phases.install]
cmds = [
  "cd backend",
  "python3 -m venv venv",
  "source venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "cd backend && source venv/bin/activate && python app.py"

