[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.setuptools", "python39Packages.wheel", "python39Packages.virtualenv"]

[phases.install]
cmds = [
  "cd backend && python3 -m venv venv",
  "cd backend && venv/bin/pip install --upgrade pip setuptools wheel",
  "cd backend && venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "cd backend && ./venv/bin/python app.py"

